// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxUELBl-VEsltM0MrKc3npJTKMyxjVYjs',
    appId: '1:212390473314:web:8151ec5b464cfe6a3feb3b',
    messagingSenderId: '212390473314',
    projectId: 'library32',
    authDomain: 'library32.firebaseapp.com',
    storageBucket: 'library32.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDf-a2bOGHricmv8_le3AjLof6QD3P8st0',
    appId: '1:212390473314:android:7166b8fd3b4c03313feb3b',
    messagingSenderId: '212390473314',
    projectId: 'library32',
    storageBucket: 'library32.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwV_Jc3AQhO-1IQPGK5c69otqZA01xxq4',
    appId: '1:212390473314:ios:ff6ed9d22637e9143feb3b',
    messagingSenderId: '212390473314',
    projectId: 'library32',
    storageBucket: 'library32.firebasestorage.app',
    iosBundleId: 'com.example.libraryUnivercity',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBwV_Jc3AQhO-1IQPGK5c69otqZA01xxq4',
    appId: '1:212390473314:ios:ff6ed9d22637e9143feb3b',
    messagingSenderId: '212390473314',
    projectId: 'library32',
    storageBucket: 'library32.firebasestorage.app',
    iosBundleId: 'com.example.libraryUnivercity',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCxUELBl-VEsltM0MrKc3npJTKMyxjVYjs',
    appId: '1:212390473314:web:9520072c046b45b73feb3b',
    messagingSenderId: '212390473314',
    projectId: 'library32',
    authDomain: 'library32.firebaseapp.com',
    storageBucket: 'library32.firebasestorage.app',
  );
}
